# Generated by Django 5.2.1 on 2025-07-04 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('date_filter', models.DateField(blank=True, null=True)),
                ('sync_all', models.BooleanField(default=False)),
                ('new_events', models.PositiveIntegerField(default=0)),
                ('updated_events', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(default='running', max_length=20)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
