# Generated by Django 5.2.3 on 2025-07-02 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AuthorizationView',
            new_name='AuthorizationModel',
        ),
    ]
