# Generated by Django 5.2.3 on 2025-06-30 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Название площадки')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Название мероприятия')),
                ('date', models.DateTimeField(verbose_name='Дата проведения мероприятия')),
                ('status', models.CharField(default='open', max_length=100, verbose_name='Текущий статус')),
                ('place', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='events.place')),
            ],
        ),
    ]
